apiVersion: v1
kind: Service
metadata:
  name: techretail-service-lb
spec:
  type: LoadBalancer # Esto solicitará una IP pública estática a Google Cloud
  selector:
    app: techretail-service
  ports:
    - protocol: TCP
      port: 80        # El puerto externo al que los usuarios accederán
      targetPort: 8080 # El puerto interno de la aplicación Spring Boot
